/*Auto generated by Kirby v1.0.0 - Sun Feb 04 2018 02:57:51 GMT-0800 (PST)
  

*/

const K = require("kirby");
const nichts_QMRK = K["nichts_QMRK"];
const not_DASH_empty = K["not_DASH_empty"];
const some_QMRK = K["some_QMRK"];
const opt_QMRK__QMRK = K["opt_QMRK__QMRK"];
const conj_BANG = K["conj_BANG"];
const MAX_DASH_INT = K["MAX_DASH_INT"];
const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.elmo.ecs.Ecs";
class EntityPool {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: Ecs.ky, line: 22
  constructor(name, engine, entity, batch) {
    (this["name"] = name, this["size"] = 0, this["next"] = 0, this["engine"] = engine, this["inuse"] = 0, this["slots"] = [], this["entity"] = entity, this["batch"] = batch);
    return this;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [take] in file: Ecs.ky, line: 29
  take() {
    let args = Array.prototype.slice.call(arguments, 0);
    if ( (this.next >= this.size) ) {
      this.grow();
    }
    let ent = kirbystdlibref.getProp(this.slots, this.next);
    (ent["status"] = true, ent["slot"] = this.next);
    (this["next"] = (this.next + 1), this["inuse"] = (this.inuse + 1));
    return this.engine.checkin.apply(this.engine, [ent].concat(args));
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [grow] in file: Ecs.ky, line: 43
  grow() {
    for (let x = 0, GS__3 = this.batch, ____break = false; ((!____break) && (x < GS__3)); x = (x + 1)) {
      conj_BANG(this.slots, new this.entity(this.engine));
    }
    return (this["size"] = (this.batch + this.size));
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [countUsed] in file: Ecs.ky, line: 50
  countUsed() {
    return this.inuse;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [poolSize] in file: Ecs.ky, line: 51
  poolSize() {
    return this.size;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [drop] in file: Ecs.ky, line: 53
  drop(ent) {
    return (ent.status ?
      (function() {
        this.engine.checkout(ent);
        (this["next"] = (this.next - 1), this["inuse"] = (this.inuse - 1));
        let tail = kirbystdlibref.getProp(this.slots, this.next);
        let slot_QUOT = kirbystdlibref.getProp(tail, "slot");
        let epos_QUOT = kirbystdlibref.getProp(ent, "slot");
        (this.slots[this.next] = ent, this.slots[epos_QUOT] = tail);
        (
        tail["slot"] = epos_QUOT);
        return (ent["slot"] = slot_QUOT, ent["status"] = false);
      }).call(this) :
      null);
  }
}
class Component {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: Ecs.ky, line: 73
  constructor() {
    let GS__4 = Array.prototype.slice.call(arguments, 0);
    let e = GS__4[0];
    (this["tpid"] = "", this["entity"] = opt_QMRK__QMRK(e, null));
    return this;
  }
}
const SystemPriority = (new Map([["PreUpdate", 100], ["NetPlay", 200], ["AI", 300], ["Motion", 400], ["Move", 500], ["Logic", 600], ["Collide", 700], ["Resolve", 800], ["Render", 900], ["Error", -1]]));
var lastId = 0;
////////////////////////////////////////////////////////////////////////////////
//fn: [generateEid] in file: Ecs.ky, line: 94
const generateEid = function(pfx) {
  let rc = ++lastId;
  if ( (!(rc < MAX_DASH_INT)) ) {
    throw new Error("too many entities");
  } else {
    null;
  }
  return [pfx, rc].join("");
};
class Engine {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: Ecs.ky, line: 101
  constructor() {
    let GS__5 = Array.prototype.slice.call(arguments, 0);
    let cfg = GS__5[0];
    (this["config"] = opt_QMRK__QMRK(cfg, null), this["updating?"] = false, this["pools"] = [], this["systems"] = [], this["ents"] = (new Map([])), this["types"] = (new Map([])));
    return this;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [checkout] in file: Ecs.ky, line: 108
  checkout(ent) {
    ent.finz();
    kirbystdlibref.dissoc_BANG(this.ents, ent.eid);
    return ent;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [checkin] in file: Ecs.ky, line: 112
  checkin(ent) {
    let args = Array.prototype.slice.call(arguments, 1);
    ent.init.apply(ent, args);
    (kirbystdlibref.assoc_BANG(this.ents, ent.eid, ent));
    return ent;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [unbind] in file: Ecs.ky, line: 116
  unbind(co, ent) {
    let cid = ((co instanceof Component) ?
      co.tpid :
      co);
    let GS__6 = kirbystdlibref.getProp(this.types, cid);
    let m = GS__6;
    if ( (!(((typeof (GS__6) === "undefined")) || ((GS__6 === null)))) ) {
      kirbystdlibref.dissoc_BANG(m, ent.eid);
    }
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [bind] in file: Ecs.ky, line: 120
  bind(co, ent) {
    let m = kirbystdlibref.getProp(this.types, co.tpid);
    if (nichts_QMRK(m)) {
      (
      m = (new Map([])));
      (kirbystdlibref.assoc_BANG(this.types, co.tpid, m));
    }
    (kirbystdlibref.assoc_BANG(m, ent.eid, co));
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [find] in file: Ecs.ky, line: 127
  find() {
    let comTypes = Array.prototype.slice.call(arguments, 0);
    let pmin = MAX_DASH_INT;
    let missed_QMRK = false;
    let pm = null;
    let ccs = [];
    let ret = [];
    let pmks,
      ccsz,
      eid,
      cid,
      c,
      sum;
    for (let i = 0, sz = kirbystdlibref.count(comTypes), ____break = false; ((!____break) && (i < sz)); i = (i + 1)) {
      (cid = comTypes[i], c = kirbystdlibref.getProp(this.types, cid));
      if (nichts_QMRK(c)) {
        (
        missed_QMRK = true);
        (
        ____break = true);
      } else {
        if (true) {
          if ( (kirbystdlibref.count(c) < pmin) ) {
            (pmin = kirbystdlibref.count(c), pm = c);
          }
          conj_BANG(ccs, c);
        }
      }
    }
    (ccsz = kirbystdlibref.count(ccs));
    if ( ((ccsz > 0) && (!missed_QMRK)) ) {
      (
      pmks = Array.from(pm.keys()));
      for (let i = 0, sz = kirbystdlibref.count(pmks), ____break = false; ((!____break) && (i < sz)); i = (i + 1)) {
        (sum = 0, eid = pmks[i]);
        for (let j = 0, ____break = false; ((!____break) && (j < ccsz)); j = (j + 1)) {
          (
          c = ccs[j]);
          if ( (c === pm) ) {
            ++sum;
          } else {
            if (kirbystdlibref.getProp(c, eid)) {
              ++sum;
            }
          }
        }
        if ( (sum === ccsz) ) {
          let GS__7 = kirbystdlibref.getProp(this.ents, eid);
          let e = GS__7;
          if ( (((typeof (GS__7) === "undefined")) || ((GS__7 === null))) ) {
            null;
          } else {
            conj_BANG(ret, e);
          }
        }
      }
    }
    return ret;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [addSystem] in file: Ecs.ky, line: 161
  addSystem(s) {
    conj_BANG(this.systems, s);
    sort(System.compare, this.systems);
    return s;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [removeSystem] in file: Ecs.ky, line: 165
  removeSystem(s) {
    let p = this.systems.indexOf(s);
    if ( (!((p < 0))) ) {
      this.systems.splice(p, 1);
      sort(System.compare, this.systems);
    }
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [deleteSystems] in file: Ecs.ky, line: 171
  deleteSystems() {
    K.resetVec_BANG(this.systems);
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [getSystem] in file: Ecs.ky, line: 174
  getSystem(s) {
    return this.systems.find(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return (s == kirbystdlibref.getProp(____args[0], "sid"));
    });
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [update] in file: Ecs.ky, line: 177
  update(time) {
    (
    this["updating?"] = true);
    let stop_QMRK = false;
    this.systems.forEach(function(s) {
      return (((!stop_QMRK) && kirbystdlibref.getProp(s, "active?")) ?
        (function() {
          return ((!s.update(time)) ?
            (stop_QMRK = true) :
            null);
        }).call(this) :
        null);
    });
    (
    this["updating?"] = false);
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [ignite] in file: Ecs.ky, line: 186
  ignite(prologue) {
    prologue();
    this.systems.forEach(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return ____args[0].preamble();
    });
    return null;
  }
}
class Entity {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: Ecs.ky, line: 193
  constructor(engine) {
    let GS__8 = Array.prototype.slice.call(arguments, 1);
    let name = GS__8[0];
    (this["slot"] = -1, this["status"] = true, this["name"] = opt_QMRK__QMRK(name, ""), this["comps"] = (new Map([])), this["engine"] = engine, this["eid"] = generateEid("ent:"));
    return this;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [init] in file: Ecs.ky, line: 202
  init() {
    let args = Array.prototype.slice.call(arguments, 0);
    return (function() {
      throw new Error("you need to override this");
    }).call(this);
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [checkin] in file: Ecs.ky, line: 204
  checkin(co) {
    if ( (!this.has_QMRK(co.tpid)) ) {
      true;
    } else {
      throw new Error("Cannot add co twice");
    }
    this.engine.bind(co, this);
    (
    co["entity"] = this);
    (kirbystdlibref.assoc_BANG(this.comps, co.tpid, co));
    return co;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [checkout] in file: Ecs.ky, line: 210
  checkout() {
    let comTypes = Array.prototype.slice.call(arguments, 0);
    let GS__9 = comTypes;
    for (let GS__11 = 0, GS__10 = false, ____break = false; ((!____break) && ((!GS__10) && (GS__11 < GS__9.length))); GS__11 = (GS__11 + 1)) {
      let c = kirbystdlibref.getProp(GS__9, GS__11);
      null;
      if ( (!true) ) {
        (
        GS__10 = true);
      } else {
        null;
      }
      if ( ((!GS__10) && true) ) {
        let GS__12 = kirbystdlibref.getProp(this.comps, c);
        let co = GS__12;
        if ( (!(((typeof (GS__12) === "undefined")) || ((GS__12 === null)))) ) {
          kirbystdlibref.dissoc_BANG(this.comps, c);
          this.engine.unbind(co, this);
        }
      }
    }
    null;
    return null;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [get] in file: Ecs.ky, line: 216
  get(comType) {
    return kirbystdlibref.getProp(this.comps, comType);
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [getAll] in file: Ecs.ky, line: 217
  getAll() {
    return Array.from(this.comps.values());
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [has?] in file: Ecs.ky, line: 218
  has_QMRK(comType) {
    return some_QMRK(kirbystdlibref.getProp(this.comps, comType));
  }
}
class System {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [update] in file: Ecs.ky, line: 223
  update(time) {
    return this.evalFunc(time);
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [compare] in file: Ecs.ky, line: 225
  compare(x, y) {
    return ((x.priority < y.priority) ?
      -1 :
      ((x.priority > y.priority) ?
        1 :
        0));
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: Ecs.ky, line: 229
  constructor(priority, engine, func) {
    (this["active?"] = true, this["evalFunc"] = func, this["engine"] = engine, this["priority"] = priority);
    return this;
  }
}
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.elmo.ecs.Ecs",
    macros: {}
  },
  EntityPool: EntityPool,
  Component: Component,
  SystemPriority: SystemPriority,
  Engine: Engine,
  Entity: Entity,
  System: System
};