/*Auto generated by Kirby v1.0.0 - Sun Feb 04 2018 02:57:18 GMT-0800 (PST)
  

*/

const ecs = require("./Ecs");
const K = require("kirby");
const some_QMRK = K["some_QMRK"];
const println = K["println"];
const runtest = K["runtest"];
const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.elmo.ecs.test";
class Leg extends ecs.Component {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: test.ky, line: 20
  constructor() {
    let GS__4 = Array.prototype.slice.call(arguments, 0);
    let n = GS__4[0];
    super(n);
    (this["tpid"] = "leg", this["length"] = 50);
    return this;
  }
}
class Arm extends ecs.Component {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: test.ky, line: 25
  constructor() {
    let GS__5 = Array.prototype.slice.call(arguments, 0);
    let n = GS__5[0];
    super(n);
    (this["tpid"] = "arm", this["length"] = 10);
    return this;
  }
}
class Person extends ecs.Entity {
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [constructor] in file: test.ky, line: 30
  constructor(e) {
    super(e);
    return this;
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [finz] in file: test.ky, line: 31
  finz() {
    return this.checkout("arm", "leg");
  }
  ////////////////////////////////////////////////////////////////////////////////
  //fn: [init] in file: test.ky, line: 33
  init() {
    let args = Array.prototype.slice.call(arguments, 0);
    this.checkin(new Arm(this));
    return this.checkin(new Leg(this));
  }
}
const engine = new ecs.Engine();
const pool1 = new ecs.EntityPool("p1", engine, Person, 6);
const ecs_DASH_test = function() {
  let ____args = Array.prototype.slice.call(arguments);
  return [kirbystdlibref.ensureTest(((pool1.poolSize() === 0)), "pool,size=0"), kirbystdlibref.ensureTest((function() {
    let x = pool1.take();
    let y = pool1.take();
    let z = pool1.take();
    return (3 === pool1.countUsed());
  }).call(this), "pool,used"), kirbystdlibref.ensureTest((function() {
    let x = pool1.take();
    let y = pool1.take();
    let z = pool1.take();
    pool1.drop(z);
    return (5 === pool1.countUsed());
  }).call(this), "pool,drop"), kirbystdlibref.ensureTest((6 === pool1.poolSize()), "pool,size>0"), kirbystdlibref.ensureTest((function() {
    let x = pool1.take();
    let y = pool1.take();
    let z = pool1.take();
    pool1.drop(x);
    return ((7 === pool1.countUsed()) && (12 === pool1.poolSize()));
  }).call(this), "pool,grow"), kirbystdlibref.ensureTest((function() {
    let x = pool1.take();
    return (x.get("leg") && (2 === kirbystdlibref.count(x.getAll())) && x.has_QMRK("leg") && x.has_QMRK("arm"));
  }).call(this), "pool,entity methods"), kirbystdlibref.ensureTest((function() {
    let a = kirbystdlibref.count(engine.find("arm"));
    let b = kirbystdlibref.count(engine.find("leg"));
    let c = kirbystdlibref.count(engine.find("arm", "leg"));
    let d = kirbystdlibref.count(engine.find("arm-and-leg"));
    console.log(["a=", a, ",b=", b, ",c=", c, ",d=", d].join(""));
    return ((a === b) && (b === c) && ((d === 0)) && ((a > 0)));
  }).call(this), "engine,find")];
};
println(runtest(ecs_DASH_test, "test: ecs"));
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.elmo.ecs.test",
    macros: {}
  },
  Leg: Leg,
  Arm: Arm,
  Person: Person,
  ecs_DASH_test: ecs_DASH_test
};