/*Auto generated by Kirby v1.0.0 - Thu Feb 15 2018 02:18:48 GMT-0800 (PST)
  czlab.elmo.core.cfg

*/

const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.elmo.core.cfg";
var cfg = {
  urlPrefix: "/public/elmo/",
  appid: "",
  color: "",
  resolution: {
    web: cc.ResolutionPolicy.SHOW_ALL,
    resDir: "sd"
  },
  levels: {},
  assets: {
    images: {},
    sheets: {},
    tiles: {},
    sounds: {
      startGame: "res/cocos2d/sfx/PowerUp"
    },
    fonts: {}
  },
  game: {
    borderTiles: "cbox-borders_x8.png",
    start: ptypes.start,
    preloadLevels_QMRK: true,
    scale: 1,
    sfx: "mp3",
    landscape_QMRK: false,
    gravity: 0,
    version: "",
    trackingID: ""
  },
  smac: null,
  l10nTable: {
    en: {
      "%mobileStart": "Press Anywhere To Start!",
      "%webStart": "Press Spacebar To Start!",
      "%passwd": "Password",
      "%userid": "UserId",
      "%player2": "Player 2",
      "%player1": "Player 1",
      "%computer": "Computer",
      "%cpu": "CPU",
      "%2players": "2 Players",
      "%1player": "1 Player",
      "%online": "Online",
      "%gameover": "Game Over",
      "%quit!": "Quit",
      "%back": "Back",
      "%ok": "OK",
      "%mmenu": "Main Menu",
      "%replay": "REPLAY",
      "%play": "PLAY",
      "%waitothers": "Waiting...\nfor other players.",
      "%waitother": "Waiting...\nfor another player.",
      "%signinplay": "Please sign in to play.",
      "%quit?": "Continue and quit game?"
    }
  },
  csts: {
    CV_X: "X".charCodeAt(0),
    CV_O: "O".charCodeAt(0),
    P2_COLOR: "O",
    P1_COLOR: "X",
    NETP: sh.gtypes.ONLINE_GAME,
    HUMAN: sh.gtypes.P1_GAME,
    BOT: sh.gtypes.P2_GAME,
    GAME_MODE: sh.gtypes.P1_GAME,
    TILE: 8,
    S_OFF: 4,
    GAME_ID: ""
  },
  sound: {
    volume: 0.5,
    open_QMRK: false,
    music: {
      volume: 0.5,
      track: null
    }
  },
  handleResolution: function(r) {},
  runOnce: function() {
    let ____args = Array.prototype.slice.call(arguments);
    return null;
  }
};
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.elmo.core.cfg",
    macros: {}
  },
  cfg: cfg
};