/*Auto generated by Kirby v1.0.0 - Mon Feb 05 2018 17:01:41 GMT-0800 (PST)
  

*/

const K = require("kirby");
const conj_BANG = K["conj_BANG"];
const modulo = K["modulo"];
const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.basal.core.Caesar";
const VISCHS = [" @N/\\Ri2}aP`(xeT4F3mt;8~%r0v:L5$+Z{'V)\"CKIc>z.*", "fJEwSU7juYg<klO&1?[h9=n,yoQGsW]BMHpXb6A|D#q^_d!-"].join("");
const VISCHS_DASH_LEN = VISCHS.length;
////////////////////////////////////////////////////////////////////////////////
//fn: [identifyChar] in file: caesar.ky, line: 14
const identifyChar = function(pos) {
  return VISCHS.charAt(pos);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [locateChar] in file: caesar.ky, line: 17
const locateChar = function(ch) {
  return (function() {
    let ret = -1;
    for (let n = 0, ____break = false; ((!____break) && (n < VISCHS_DASH_LEN)); n = (n + 1)) {
      if ( (ch === VISCHS.charAt(n)) ) {
        (
        ret = n);
        (
        ____break = true);
      }
    }
    return ret;
  }).call(this);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [slideForward] in file: caesar.ky, line: 25
const slideForward = function(delta, cpos) {
  let ptr = (cpos + delta);
  return identifyChar(((ptr >= VISCHS_DASH_LEN) ?
    (ptr - VISCHS_DASH_LEN) :
    ptr));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [slideBack] in file: caesar.ky, line: 32
const slideBack = function(delta, cpos) {
  let ptr = (cpos - delta);
  return identifyChar(((ptr < 0) ?
    (VISCHS_DASH_LEN + ptr) :
    ptr));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [shiftEnc] in file: caesar.ky, line: 40
const shiftEnc = function(shiftpos, delta, cpos) {
  return ((shiftpos < 0) ?
    slideForward(delta, cpos) :
    slideBack(delta, cpos));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [shiftDec] in file: caesar.ky, line: 46
const shiftDec = function(shiftpos, delta, cpos) {
  return ((shiftpos < 0) ?
    slideBack(delta, cpos) :
    slideForward(delta, cpos));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [encrypt] in file: caesar.ky, line: 52
const encrypt = function(src, shiftpos) {
  let out = [];
  if ( (((typeof (src) === "string")) && not_DASH_empty(src) && (0 !== shiftpos)) ) {
    let delta = modulo(Math.abs(shiftpos), VISCHS_DASH_LEN);
    let len = src.length;
    let p,
      ch;
    for (let n = 0, ____break = false; ((!____break) && (n < len)); n = (n + 1)) {
      (ch = src.charAt(n), p = locateChar(ch));
      if ( (!(p < 0)) ) {
        (
        ch = shiftEnc(shiftpos, delta, p));
      } else {
        null;
      }
      conj_BANG(out, ch);
    }
  }
  return out.join("");
};
////////////////////////////////////////////////////////////////////////////////
//fn: [decrypt] in file: caesar.ky, line: 70
const decrypt = function(cipher, shiftpos) {
  let out = [];
  if ( (((typeof (cipher) === "string")) && not_DASH_empty(cipher) && (0 !== shiftpos)) ) {
    let delta = modulo(Math.abs(shiftpos), VISCHS_DASH_LEN);
    let len = cipher.length;
    let p,
      ch;
    for (let n = 0, ____break = false; ((!____break) && (n < len)); n = (n + 1)) {
      (ch = cipher.charAt(n), p = locateChar(ch));
      if ( (!(p < 0)) ) {
        (
        ch = shiftDec(shiftpos, delta, p));
      } else {
        null;
      }
      conj_BANG(out, ch);
    }
  }
  return out.join("");
};
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.basal.core.Caesar",
    macros: {}
  },
  encrypt: encrypt,
  decrypt: decrypt
};